// Neon Runner – simple endless runner on canvas#game
// Enhanced graphics: gradient background, neon glow, lane markers, jump particles
// Author: generated by OpenAI
(() => {
  const canvas = document.getElementById('game');
  if (!canvas) return; // canvas missing
  const ctx = canvas.getContext('2d');
  const width = canvas.width = canvas.offsetWidth || 800;
  const height = canvas.height = canvas.offsetHeight || 400;

  // Game constants
  const LANE_COUNT = 3;
  const LANE_WIDTH = width / LANE_COUNT;
  const PLAYER_SIZE = 30;
  const GRAVITY = 0.6;
  const JUMP_VELOCITY = -12;
  const OBSTACLE_FREQ = 120; // frames
  const SPEED = 3; // base speed (pixels per frame)
  // Audio setup
  const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  function playTone(freq, length) {
    if (audioCtx.state === 'suspended') audioCtx.resume();
    const osc = audioCtx.createOscillator();
    const gain = audioCtx.createGain();
    osc.frequency.value = freq;
    osc.type = 'square';
    osc.connect(gain);
    gain.connect(audioCtx.destination);
    gain.gain.setValueAtTime(0.1, audioCtx.currentTime);
    osc.start();
    osc.stop(audioCtx.currentTime + length);
  }

  // Player state
  const player = {
    lane: 1, // middle lane
    y: height - PLAYER_SIZE,
    vy: 0,
    width: PLAYER_SIZE,
    height: PLAYER_SIZE,
    lives: 3,
    score: 0,
    jumping: false,
  };

  const obstacles = [];
  const particles = [];
  let frame = 0;
  let gameOver = false;

  // Input handling
  const keys = new Set();
  window.addEventListener('keydown', e => {
    keys.add(e.key);
    if (e.key === 'ArrowLeft') moveLane(-1);
    if (e.key === 'ArrowRight') moveLane(1);
    if (e.key === ' ' || e.key === 'Spacebar') jump();
  });
  window.addEventListener('keyup', e => keys.delete(e.key));

  function moveLane(dir) {
    const newLane = player.lane + dir;
    if (newLane >= 0 && newLane < LANE_COUNT) player.lane = newLane;
  }
  function jump() {
    if (!player.jumping) {
      player.vy = JUMP_VELOCITY;
      player.jumping = true;
      // spawn jump particles
      const px = player.lane * LANE_WIDTH + LANE_WIDTH / 2;
      for (let i = 0; i < 8; i++) {
        particles.push({
          x: px + (Math.random() - 0.5) * 10,
          y: player.y + PLAYER_SIZE,
          vy: -2 - Math.random() * 2,
          radius: 3 + Math.random() * 2,
          color: '#0ff',
          alpha: 1,
        });
      }
      // play jump sound
      playTone(300, 0.08);
    }
  }


  function spawnObstacle() {
    const lane = Math.floor(Math.random() * LANE_COUNT);
    const size = PLAYER_SIZE;
    obstacles.push({
      lane,
      x: lane * LANE_WIDTH + (LANE_WIDTH - size) / 2,
      y: -size,
      width: size,
      height: size,
    });
  }

  function update() {
  // update particles
  for (let i = particles.length - 1; i >= 0; i--) {
    const p = particles[i];
    p.y += p.vy;
    p.alpha -= 0.02;
    if (p.alpha <= 0) particles.splice(i, 1);
  }
    if (gameOver) return;
    // player physics
    player.y += player.vy;
    player.vy += GRAVITY;
    const groundY = height - PLAYER_SIZE;
    if (player.y >= groundY) {
      player.y = groundY;
      player.vy = 0;
      player.jumping = false;
    }
    // obstacles
    if (frame % OBSTACLE_FREQ === 0) spawnObstacle();
    for (let i = obstacles.length - 1; i >= 0; i--) {
      const o = obstacles[i];
      o.y += SPEED;
      // remove off-screen
      if (o.y > height) obstacles.splice(i, 1);
    }
    // collision
    const playerRect = {
      x: player.lane * LANE_WIDTH + (LANE_WIDTH - player.width) / 2,
      y: player.y,
      w: player.width,
      h: player.height,
    };
    for (const o of obstacles) {
        if (rectIntersect(playerRect, o)) {
          player.lives--;
          obstacles.splice(obstacles.indexOf(o), 1);
          // play hit sound
          playTone(150, 0.2);
          if (player.lives <= 0) {
            gameOver = true;
            // play game over sound
            playTone(100, 0.5);
          }
        }
    }
    player.score++;
    frame++;
  }

  function rectIntersect(a, b) {
    return a.x < b.x + b.width && a.x + a.w > b.x && a.y < b.y + b.height && a.y + a.h > b.y;
  }

  function draw() {
    // clear with gradient background
    const bgGrad = ctx.createLinearGradient(0, 0, 0, height);
    bgGrad.addColorStop(0, '#001');
    bgGrad.addColorStop(1, '#003');
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, width, height);
    // neon lane markers
    ctx.strokeStyle = '#0ff';
    ctx.lineWidth = 2;
    ctx.setLineDash([10, 10]);
    for (let i = 1; i < LANE_COUNT; i++) {
      ctx.beginPath();
      ctx.moveTo(i * LANE_WIDTH, 0);
      ctx.lineTo(i * LANE_WIDTH, height);
      ctx.stroke();
    }
    // player with neon glow
    ctx.save();
    ctx.shadowColor = '#0ff';
    ctx.shadowBlur = 20;
    ctx.fillStyle = '#0ff';
    const px = player.lane * LANE_WIDTH + (LANE_WIDTH - player.width) / 2;
    ctx.fillRect(px, player.y, player.width, player.height);
    ctx.restore();
    // obstacles with neon glow
    ctx.save();
    ctx.shadowColor = '#f00';
    ctx.shadowBlur = 15;
    ctx.fillStyle = '#f0f'; // magenta neon for variety
    for (const o of obstacles) {
      ctx.fillRect(o.x, o.y, o.width, o.height);
    }
    ctx.restore();
    // UI
    ctx.fillStyle = '#fff';
    ctx.font = '16px monospace';
    ctx.fillText(`Score: ${player.score}`, 10, 20);
    ctx.fillText(`Lives: ${player.lives}`, 10, 40);
    // particles
    for (const p of particles) {
      ctx.save();
      ctx.globalAlpha = p.alpha;
      ctx.fillStyle = p.color;
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
      ctx.fill();
      ctx.restore();
    }
    if (gameOver) {
      ctx.fillStyle = 'rgba(0,0,0,0.7)';
      ctx.fillRect(0, 0, width, height);
      ctx.fillStyle = '#f00';
      ctx.textAlign = 'center';
      ctx.font = '32px monospace';
      ctx.fillText('Game Over', width / 2, height / 2);
    }
  }

  function loop() {
    update();
    draw();
    if (!gameOver) requestAnimationFrame(loop);
  }
  requestAnimationFrame(loop);
})();
